LOGIN_FIELD = ("xpath", '//input[@id="user-name"]')
PASSWORD_FIELD = ("xpath", '//input[@id="password"]')
lOGIN_BTN = ("xpath", '//input[@type="submit"]')
LOGIN_ERROR_MESSAGE = ("xpath", '//h3[@data-test="error"]')
BURGER_MENU = ("xpath", '//button[@id="react-burger-menu-btn"]')
LOGOUT = ("xpath", '//a[@id="logout_sidebar_link"]')
ABOUT = ("xpath", '//a[@id="about_sidebar_link"]')
ADD_TO_CARD_BTM = ("xpath", '(//button[contains(@class,"btn")])[1]')
ADD_TO_CARD_BTM_IN_INVENTORY_DTL = ("xpath", '(//button[contains(@class,"btn")])[2]')
CARD = ("xpath", '//div[@id="shopping_cart_container"]')
ITEM_NAME = ("xpath", '(//div[@class="inventory_item_name "])[1]')
ITEM_TITLE_LINK = ("xpath", '//a[@id="item_4_title_link"]')
ITEM_IMG_LINK = ("xpath", '//a[@id="item_4_img_link"]')
ITEM_NAME_IN_CARD = ("xpath", '(//div[@class="inventory_item_name"])[1]')
INVENTORY_NAME = ("xpath", '//div[contains(@class, "large_size")]')
CHECKOUT_BTN = ("xpath", '//button[contains(@class,"checkout_button ")]')
FERST_NAME = ("xpath", '//input[@id="first-name"]')
lAST_NAME = ("xpath", '//input[@id="last-name"]')
ZIP = ("xpath", '//input[@id="postal-code"]')
CONTINUE_BTN = ("xpath", '//input[@id="continue"]')
FINISH_BTN = ("xpath", '//button[@id="finish"]')
THANK_TEXT = ("xpath", '//h2[@class="complete-header"]')
DROPDOWN_ELEMENT = ("xpath", '//select[@class="product_sort_container"]')
